### ISSUE TITLE
Video-downloader dont start on Ubuntu Mate 18.04

### ISSUE THREAD

**Issue by PatoSalvaje** [Unrud/video-downloader#4]
Trying to run Video downloader on Ubuntu Mate 18.04 by terminal shows an error:

Traceback (most recent call last):
  File "/snap/video-downloader/182/usr/local/bin/video-downloader", line 38, in <module>
    main.main(VERSION)
  File "/snap/video-downloader/182/usr/local/share/video-downloader/video_downloader/main.py", line 140, in main
    app = App()
  File "/snap/video-downloader/182/usr/local/share/video-downloader/video_downloader/main.py", line 51, in __init__
    BaseWindowMixin.__init__(self, Platform(self, [f1, f2]))
  File "/snap/video-downloader/182/usr/local/share/video-downloader/video_downloader/platform.py", line 36, in __init__
    self._set_X_scaling()
  File "/snap/video-downloader/182/usr/local/share/video-downloader/video_downloader/platform.py", line 74, in _set_X_scaling
    xdpi = int(rdb.get("Xft.dpi", "Xft.dpi", BASE_DPI))
ValueError: invalid literal for int() with base 10: '84.0458984375'

With sudo:
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "/snap/video-downloader/182/usr/local/bin/video-downloader", line 38, in <module>
    main.main(VERSION)
  File "/snap/video-downloader/182/usr/local/share/video-downloader/video_downloader/main.py", line 140, in main
    app = App()
  File "/snap/video-downloader/182/usr/local/share/video-downloader/video_downloader/main.py", line 44, in __init__
    tk.Tk.__init__(self)
  File "/snap/video-downloader/182/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0.0"

With Ubuntu (gnome) video downloader is running ok

**Comment by Unrud** [comment]
Should be fixed in release 0.1.7.
